#-----------------------------------------------
#GitHub Actions Part-1 - Basics
#
#Copyleft (c) by Yevgeny Korban 2024
#-----------------------------------------------

name: My-GitHubActions-Basics
env:
  APPLICATION_NAME: "MyFlask"
  DEPLOY_PACKAGE_NAME: "flask-deploy-file-ver-${{ github.sha }}"

on:
  push:
    branches:
      - main

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print_Message1
      run: echo "Hello World, it's message from Testing job"
    
    - name: Execute few command
      run: |
        echo "Hello message1"
        echo "Hello message2"
        echo "Application name is: ${{ env.APPLICATION_NAME }}"
      
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    
    steps:
    - name: Print_Message2
      run: echo "It's message from Deploy job"
    
    - name: Printing deployment package
      run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }} 


