#-----------------------------------------------
#GitHub Actions Part-1 - Basics
#
#Copyleft (c) by Yevgeny Korban 2024
#-----------------------------------------------

name: My-GitHubActions-Basics
env:
  APPLICATION_NAME: "MyFlask"
  DEPLOY_PACKAGE_NAME: "flask-deploy-file-ver-${{ github.sha }}"

on:
  push:
    branches:
      - main

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print_Message1
      run: echo "Hello World, it's message from Testing job"
    
    - name: Execute few command
      run: |
        echo "Hello message1"
        echo "Hello message2"
        echo "Application name is: ${{ env.APPLICATION_NAME }}"

      


    - name: Git clone my repo
      uses: actions/checkout@v1

    - name: Show list files in current folder
      run: ls -la

      
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    env:
      VAR1 : "This's Job level variable1"
      VAR2 : "This's Job level variable2"
    
    steps:
    - name: Print_Message2
      run: echo "It's message from Deploy job"
    
    - name: Printing deployment package
      run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}" 

    - name: Let's test some package1 if it is here
      run: aws --version

    - name: Let's test some package2 if it is here
      run: zip --version

    - name: Print env vars
      run: |
        echo "Var1 = ${{ env.VAR1 }}"
        echo "Var2 = ${{ env.VAR2 }}"

      env:
        LOCAL_VAR: "This's local env_variable in this step"
      - name: Print local var
        run: echo "Var3 = $LOCAL_VAR"
      
